alias rm='rm -v'
alias mv='mv -v'
alias cp='cp -v'
[[ $(uname -s) == "Darwin" ]] && alias chmod='chmod -v' || alias chown='chown -cv'
alias ln='ln -v'
alias pip='pip3'
alias py='python3'
alias python='python3'
