[[ $(uname -s) == "Darwin" ]] && alias chmod='chmod -v' || alias chmod='chmod -cv'
[[ $(uname -s) == "Darwin" ]] && alias chown='chown -v' || alias chown='chown -cv'
alias cp='cp -v'
alias ln='ln -v'
[[ $(uname -s) == "Darwin" ]] && alias ls='ls -G'
alias mv='mv -v'
alias pip='pip3'
alias py='python3'
alias python='python3'
alias rm='rm -v'
